version: 2
jobs:
    build:
        docker:
            - image: circleci/node:12.9
        steps:
            - checkout
            - deploy:
                  name: Digital Ocean
                  command: ssh -o "StrictHostKeyChecking no" perfest@167.71.234.128 "bash deploy-backend.sh"
